---
galaxy_info:
  author: Dreadnode
  namespace: dreadnode
  description: Install and configure credential access tooling for Ares agents
  company: dreadnode
  license: MIT
  role_name: credential_access_tools
  min_ansible_version: "2.18.4"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Kali
      versions:
        - all
  galaxy_tags:
    - ares
    - security
    - pentesting
    - activedirectory
    - credentials
    - kerberos
    - kali

dependencies:
  - role: dreadnode.nimbus_range.base
