---
area/templates:
  - changed-files:
      - any-glob-to-any-file: "warpgate-templates/**/*"

area/docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**/*"
      - any-glob-to-any-file: "README.md"

area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

area/pre-commit:
  - changed-files:
      - any-glob-to-any-file: .pre-commit-config.yaml
      - any-glob-to-any-file: .hooks/**/*
