---
galaxy_info:
  author: Dreadnode
  company: Dreadnode
  description: Configure SACL auditing on Domain Controllers for attack detection
  license: proprietary
  min_ansible_version: "2.14"
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
  galaxy_tags:
    - windows
    - activedirectory
    - security
    - auditing
    - dcsync

dependencies: []
