---
- name: Check if SSM agent service is already installed (Windows)
  ansible.windows.win_service:
    name: AmazonSSMAgent
  register: aws_ssm_agent_service
  failed_when: false

- name: Download SSM agent installer (Windows)
  ansible.windows.win_get_url:
    url: "{{ aws_ssm_agent_windows_install_url }}"
    dest: "{{ aws_ssm_agent_windows_temp_dir }}\\{{ aws_ssm_agent_windows_installer }}"
  when: not (aws_ssm_agent_service.exists | default(false))

- name: Install SSM agent (Windows)
  ansible.windows.win_package:
    path: "{{ aws_ssm_agent_windows_temp_dir }}\\{{ aws_ssm_agent_windows_installer }}"
    arguments: /S
    state: present
  when: not (aws_ssm_agent_service.exists | default(false))

- name: Make sure SSM agent service is running (Windows)
  ansible.windows.win_service:
    name: AmazonSSMAgent
    start_mode: auto
    state: started

- name: Clean up temporary files (Windows)
  ansible.windows.win_file:
    path: "{{ aws_ssm_agent_windows_temp_dir }}\\{{ aws_ssm_agent_windows_installer }}"
    state: absent
  register: aws_ssm_agent_cleanup
  failed_when: false
  when: not (aws_ssm_agent_service.exists | default(false))
