---
- name: Restart cloudwatch_agent (Linux)
  ansible.builtin.systemd:
    name: amazon-cloudwatch-agent
    state: restarted
  become: true
  when: ansible_os_family != 'Windows'

- name: Restart cloudwatch_agent (Windows)
  ansible.windows.win_service:
    name: AmazonCloudWatchAgent
    state: restarted
  when: ansible_os_family == 'Windows'
