//! Detection template catalog — listing and lookup.

use anyhow::Result;
use serde_json::Value;

use crate::ToolOutput;

/// List all available detection templates with MITRE mappings.
pub async fn list_detection_templates(_args: &Value) -> Result<ToolOutput> {
    let templates: &[(&str, &str, &str, &str, Option<&str>)] = &[
        // (name, mitre, tactic, severity, red_team_tool)
        // ── Reconnaissance ──
        (
            "detect_port_scanning",
            "T1046",
            "discovery",
            "medium",
            Some("nmap_scan"),
        ),
        (
            "detect_user_enumeration",
            "T1087.002",
            "discovery",
            "medium",
            Some("enumerate_users"),
        ),
        (
            "detect_account_enumeration",
            "T1087.002",
            "discovery",
            "medium",
            Some("enumerate_users"),
        ),
        (
            "detect_share_enumeration",
            "T1135",
            "discovery",
            "medium",
            Some("enumerate_shares"),
        ),
        // ── Credential Access ──
        (
            "detect_secretsdump",
            "T1003",
            "credential_access",
            "critical",
            Some("secretsdump"),
        ),
        (
            "detect_dcsync",
            "T1003.006",
            "credential_access",
            "critical",
            Some("secretsdump"),
        ),
        (
            "detect_dcsync_replication",
            "T1003.006",
            "credential_access",
            "critical",
            Some("secretsdump"),
        ),
        (
            "detect_kerberoasting",
            "T1558.003",
            "credential_access",
            "high",
            Some("kerberoast"),
        ),
        (
            "detect_asrep_roasting",
            "T1558.004",
            "credential_access",
            "high",
            Some("asrep_roast"),
        ),
        (
            "detect_asrep_roasting_bulk",
            "T1558.004",
            "credential_access",
            "high",
            Some("asrep_roast"),
        ),
        (
            "detect_brute_force",
            "T1110",
            "credential_access",
            "medium",
            None,
        ),
        (
            "detect_password_spray",
            "T1110",
            "credential_access",
            "medium",
            None,
        ),
        (
            "detect_s4u_delegation",
            "T1558.003",
            "credential_access",
            "critical",
            Some("get_st"),
        ),
        (
            "detect_lsa_secrets_access",
            "T1003.004",
            "credential_access",
            "high",
            Some("secretsdump"),
        ),
        (
            "detect_ntlm_relay",
            "T1557",
            "credential_access",
            "high",
            Some("ntlmrelayx"),
        ),
        (
            "detect_certificate_authentication",
            "T1649",
            "credential_access",
            "high",
            Some("certipy_auth"),
        ),
        // ── Lateral Movement ──
        (
            "detect_pass_the_hash",
            "T1550.002",
            "lateral_movement",
            "high",
            Some("domain_admin_checker"),
        ),
        (
            "detect_lateral_movement",
            "T1021",
            "lateral_movement",
            "high",
            None,
        ),
        (
            "detect_smb_file_access",
            "T1039",
            "collection",
            "medium",
            Some("download_file_content"),
        ),
        // ── Privilege Escalation ──
        (
            "detect_adcs_exploitation",
            "T1649",
            "privilege_escalation",
            "high",
            Some("certipy_*"),
        ),
        (
            "detect_certificate_abuse",
            "T1649",
            "privilege_escalation",
            "high",
            Some("certipy_*"),
        ),
        (
            "detect_delegation_abuse",
            "T1134.001",
            "privilege_escalation",
            "high",
            Some("rbcd_write"),
        ),
        // ── Persistence ──
        (
            "detect_golden_ticket",
            "T1558.001",
            "persistence",
            "critical",
            Some("generate_golden_ticket"),
        ),
        // ── Execution ──
        (
            "detect_suspicious_execution",
            "T1059",
            "execution",
            "medium",
            None,
        ),
        (
            "detect_service_creation",
            "T1543.003",
            "execution",
            "high",
            Some("psexec"),
        ),
        (
            "detect_scheduled_task",
            "T1053.005",
            "execution",
            "medium",
            Some("atexec"),
        ),
        (
            "detect_remote_registry_start",
            "T1569.002",
            "execution",
            "medium",
            Some("secretsdump"),
        ),
        // ── ADCS/Certipy Specific ──
        (
            "detect_certipy_enumeration",
            "T1649",
            "discovery",
            "medium",
            Some("certipy_find"),
        ),
        (
            "detect_esc1_attack",
            "T1649",
            "privilege_escalation",
            "critical",
            Some("certipy_req_esc1"),
        ),
        (
            "detect_esc4_attack",
            "T1649",
            "privilege_escalation",
            "high",
            None,
        ),
        (
            "detect_esc8_attack",
            "T1649",
            "privilege_escalation",
            "critical",
            Some("ntlmrelayx"),
        ),
        // ── BloodHound Specific ──
        (
            "detect_bloodhound",
            "T1087",
            "discovery",
            "medium",
            Some("run_bloodhound"),
        ),
        (
            "detect_bloodhound_collection",
            "T1087",
            "discovery",
            "medium",
            Some("run_bloodhound"),
        ),
        (
            "detect_bloodhound_domain_enum",
            "T1482",
            "discovery",
            "medium",
            Some("run_bloodhound"),
        ),
        (
            "detect_bloodhound_acl_enum",
            "T1069.002",
            "discovery",
            "medium",
            Some("run_bloodhound"),
        ),
        (
            "detect_bloodhound_session_enum",
            "T1033",
            "discovery",
            "medium",
            Some("run_bloodhound"),
        ),
        (
            "detect_bloodhound_gpo_enum",
            "T1615",
            "discovery",
            "medium",
            Some("run_bloodhound"),
        ),
        (
            "detect_bloodhound_computer_enum",
            "T1018",
            "discovery",
            "medium",
            Some("run_bloodhound"),
        ),
        // ── Impacket Tool Fingerprints ──
        (
            "detect_impacket_wmiexec",
            "T1047",
            "execution",
            "high",
            Some("wmiexec"),
        ),
        (
            "detect_impacket_psexec",
            "T1569.002",
            "execution",
            "high",
            Some("psexec"),
        ),
        (
            "detect_impacket_smbexec",
            "T1569.002",
            "execution",
            "high",
            Some("smbexec"),
        ),
        (
            "detect_impacket_atexec",
            "T1053.002",
            "execution",
            "medium",
            Some("atexec"),
        ),
        (
            "detect_impacket_dcomexec",
            "T1021.003",
            "lateral_movement",
            "high",
            Some("dcomexec"),
        ),
        (
            "detect_impacket_secretsdump_sam",
            "T1003.002",
            "credential_access",
            "high",
            Some("secretsdump"),
        ),
        (
            "detect_impacket_secretsdump_lsa",
            "T1003.004",
            "credential_access",
            "high",
            Some("secretsdump"),
        ),
        (
            "detect_impacket_ntlmrelayx",
            "T1557.001",
            "credential_access",
            "high",
            Some("ntlmrelayx"),
        ),
        (
            "detect_impacket_smbclient",
            "T1021.002",
            "lateral_movement",
            "medium",
            Some("smbclient"),
        ),
        // ── Investigation ──
        ("get_host_activity", "-", "investigation", "-", None),
        ("get_user_activity", "-", "investigation", "-", None),
    ];

    let formatted: Vec<String> = templates
        .iter()
        .map(|(name, mitre, tactic, severity, tool)| {
            let tool_str = tool.unwrap_or("-");
            format!("- **{name}** [{mitre}] ({tactic}) severity={severity} tool={tool_str}")
        })
        .collect();

    Ok(ToolOutput {
        stdout: format!(
            "Available detection templates ({}):\n\n{}",
            templates.len(),
            formatted.join("\n")
        ),
        stderr: String::new(),
        exit_code: Some(0),
        success: true,
    })
}
