---
# Linux
aws_ssm_agent_linux_install_url: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb"
aws_ssm_agent_install_packages:
  - systemd

# Windows
aws_ssm_agent_windows_install_url: "https://amazon-ssm-{{ aws_ssm_agent_aws_region | default('us-east-1') }}.s3.amazonaws.com/latest/windows_amd64/AmazonSSMAgentSetup.exe"
aws_ssm_agent_windows_temp_dir: "C:\\Windows\\Temp"
aws_ssm_agent_windows_installer: "SSMAgent_latest.exe"
