---
# General settings
aws_cloudwatch_agent_temp_dir: "/tmp/cloudwatch_install"

# Linux
aws_cloudwatch_agent_linux_config_dir: "/opt/aws/amazon-cloudwatch-agent/etc"
aws_cloudwatch_agent_linux_log_dir: "/var/log/amazon/amazon-cloudwatch-agent"

# Windows
aws_cloudwatch_agent_windows_temp_dir: "C:\\Windows\\Temp"
aws_cloudwatch_agent_windows_installer: "amazon-cloudwatch-agent.msi"
aws_cloudwatch_agent_windows_config_dir: "C:\\ProgramData\\Amazon\\AmazonCloudWatchAgent"
aws_cloudwatch_agent_windows_log_dir: "C:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\Logs"

# CloudWatch agent configuration
aws_cloudwatch_agent_config:
  agent:
    metrics_collection_interval: 60
    run_as_user: "root"
  metrics:
    metrics_collected:
      cpu:
        measurement:
          - "cpu_usage_idle"
          - "cpu_usage_iowait"
          - "cpu_usage_user"
          - "cpu_usage_system"
        resources: ["*"]
        totalcpu: true
      disk:
        measurement:
          - "used_percent"
          - "inodes_free"
        resources: ["*"]
      diskio:
        measurement:
          - "io_time"
          - "write_bytes"
          - "read_bytes"
          - "writes"
          - "reads"
        resources: ["*"]
      mem:
        measurement:
          - "mem_used_percent"
      swap:
        measurement:
          - "swap_used_percent"
      netstat:
        measurement:
          - "tcp_established"
          - "tcp_time_wait"
      processes:
        measurement:
          - "running"
          - "blocked"
          - "zombies"
    append_dimensions:
      InstanceId: "${aws:InstanceId}"
      InstanceType: "${aws:InstanceType}"
      AutoScalingGroupName: "${aws:AutoScalingGroupName}"
