#!/usr/bin/env bash
# Regenerate .env from AWS Secrets Manager.
#
#   ./scripts/env-from-secrets.sh                # writes ./.env
#   ./scripts/env-from-secrets.sh path/to/.env   # writes given path
#
# Reads the JSON secret at $ARES_SECRETS_ID (default: ares/api-keys) using
# AWS_PROFILE/AWS_REGION (defaults: lab / us-west-1) and merges in the
# non-secret defaults / placeholders from .env.example.
set -euo pipefail

AWS_PROFILE="${AWS_PROFILE:-lab}"
AWS_REGION="${AWS_REGION:-us-west-1}"
SECRETS_ID="${ARES_SECRETS_ID:-ares/api-keys}"
OUT="${1:-.env}"

if ! command -v jq >/dev/null; then
	echo "error: jq is required" >&2
	exit 1
fi

secrets_json=$(AWS_PROFILE="$AWS_PROFILE" AWS_REGION="$AWS_REGION" \
	aws secretsmanager get-secret-value \
	--secret-id "$SECRETS_ID" \
	--query SecretString --output text)

get() { echo "$secrets_json" | jq -r --arg k "$1" '.[$k] // ""'; }

OPENAI_API_KEY=$(get OPENAI_API_KEY)
ANTHROPIC_API_KEY=$(get ANTHROPIC_API_KEY)
GRAFANA_URL=$(get GRAFANA_URL)
GRAFANA_SERVICE_ACCOUNT_TOKEN=$(get GRAFANA_SERVICE_ACCOUNT_TOKEN)
LOKI_URL=$(get LOKI_URL)
LOKI_AUTH_TOKEN=$(get LOKI_AUTH_TOKEN)
DREADNODE_API_KEY=$(get DREADNODE_API_KEY)
DREADNODE_SERVER_URL=$(get DREADNODE_SERVER_URL)
[ -n "$DREADNODE_SERVER_URL" ] || DREADNODE_SERVER_URL="https://platform.dreadnode.io"

cat >"$OUT" <<EOF
# Generated by scripts/env-from-secrets.sh from AWS Secrets Manager ($SECRETS_ID).
# Re-run the script to refresh. Do not commit.

# ── LLM API keys ──
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY

# ── Observability ──
GRAFANA_URL=$GRAFANA_URL
GRAFANA_SERVICE_ACCOUNT_TOKEN=$GRAFANA_SERVICE_ACCOUNT_TOKEN
LOKI_URL=$LOKI_URL
LOKI_AUTH_TOKEN=$LOKI_AUTH_TOKEN

# ── Dreadnode platform ──
DREADNODE_API_KEY=$DREADNODE_API_KEY
DREADNODE_SERVER_URL=$DREADNODE_SERVER_URL

# ── EC2 deploy ──
S3_BUCKET=ares-benchmark-us-west-1

# ── Benchmark replay (AWS infra — lab defaults; override for other envs) ──
BENCHMARK_SECURITY_GROUP_ID=sg-0188cbee650cec0ea
BENCHMARK_INSTANCE_PROFILE=ares-benchmark-replay
BENCHMARK_SUBNET_ID=subnet-092c9b9a49a4e549f
# BENCHMARK_S3_BUCKET=ares-benchmark-us-west-1
# BENCHMARK_AWS_PROFILE=lab
# BENCHMARK_AWS_REGION=us-west-1
# BENCHMARK_INSTANCE_TYPE=t3.medium
# ARES_SECRETS_ID=ares/api-keys
EOF

chmod 600 "$OUT"
echo "wrote $OUT from $SECRETS_ID ($AWS_PROFILE/$AWS_REGION)"
