---
- name: Download CloudWatch agent installer (Windows)
  ansible.windows.win_get_url:
    url: "{{ aws_cloudwatch_agent_win_url }}"
    dest: "{{ aws_cloudwatch_agent_windows_temp_dir }}\\{{ aws_cloudwatch_agent_windows_installer }}"

- name: Install CloudWatch agent (Windows)
  ansible.windows.win_package:
    path: "{{ aws_cloudwatch_agent_windows_temp_dir }}\\{{ aws_cloudwatch_agent_windows_installer }}"
    arguments: /quiet
    state: present

- name: Ensure CloudWatch Agent config directory exists
  ansible.windows.win_file:
    path: "{{ aws_cloudwatch_agent_windows_config_dir }}"
    state: directory

- name: Create CloudWatch Agent configuration (Windows)
  ansible.windows.win_template:
    src: amazon-cloudwatch-agent.json.j2
    dest: "{{ aws_cloudwatch_agent_windows_config_dir }}\\amazon-cloudwatch-agent.json"
  notify: Restart cloudwatch_agent (Windows)

- name: Start CloudWatch Agent (Windows)
  ansible.windows.win_shell: |
    & "C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1" -a fetch-config -m ec2 -s -c file:"{{ aws_cloudwatch_agent_windows_config_dir }}\amazon-cloudwatch-agent.json"
  args:
    creates: "{{ aws_cloudwatch_agent_windows_config_dir }}\\amazon-cloudwatch-agent.json.status"

- name: Make sure CloudWatch agent service is running (Windows)
  ansible.windows.win_service:
    name: AmazonCloudWatchAgent
    start_mode: auto
    state: started

- name: Clean up temporary files (Windows)
  ansible.windows.win_file:
    path: "{{ aws_cloudwatch_agent_windows_temp_dir }}\\{{ aws_cloudwatch_agent_windows_installer }}"
    state: absent
