---
galaxy_info:
  author: Jayson Grace
  namespace: dreadnode
  description: Install and configure AWS CloudWatch Agent
  company: dreadnode
  license: MIT
  role_name: aws_cloudwatch_agent
  min_ansible_version: "2.18.4"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - aws
    - cloudwatch
    - linux
    - monitoring
    - windows
