---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Include default variables
      ansible.builtin.include_vars:
        file: "../../defaults/main.yml"

    - name: Include base role (prerequisite for pipx, Rust)
      ansible.builtin.include_role:
        name: dreadnode.nimbus_range.base
      vars:
        base_install_pipx: true
        base_install_rust: true

    - name: Include role under test
      ansible.builtin.include_role:
        name: dreadnode.nimbus_range.recon_tools
