---
galaxy_info:
  author: Jayson Grace
  namespace: dreadnode
  description: Install and configure AWS SSM Agent
  company: dreadnode
  license: MIT
  role_name: aws_ssm_agent
  min_ansible_version: "2.18.4"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - aws
    - linux
    - monitoring
    - ssm
    - windows
